### ISSUE TITLE
Server showing as offline

### ISSUE THREAD

**Issue by rxbyy** [MineTrax/minetrax#395]
Alright. In the Picture you can see the the server is shown as offline, yes i have the right ip adress in the config.yml in my BungeeCord, also of course i have query enabled and all that. still showing its not workin

![image](https://github.com/user-attachments/assets/0ce00487-c7f0-49ce-8ba6-1c0f527840f5)

**Comment by Xinecraft** [comment]
Try entering your IP:PORT in some PING check site like https://mcsrvstat.us/ and see if it show online there.
Most likely its not accessible from web and you might consider changing config to let Minetrax do PING via hostname (eg: play.xxxxxxxxx.com) instead.

To force Minetrax to PING proxy using hostname instead of ip:port plz change this .env variable to `false`.
```
PING_PROXY_SERVER_USING_IP_ADDRESS=false
```

and then run update once.
```
cd /var/www/minetrax
sh update.sh
```

**Comment by rxbyy** [comment]
I activated that and it didnt worked

Zishan ***@***.***> schrieb am Sa., 28. Sept. 2024, 07:47:

**Comment by rxbyy** [comment]
> Try entering your IP:PORT in some PING check site like https://mcsrvstat.us/ and see if it show online there. Most likely its not accessible from web and you might consider changing config to let Minetrax do PING via hostname (eg: play.xxxxxxxxx.com) instead.
> 
> To force Minetrax to PING proxy using hostname instead of ip:port plz change this .env variable to `false`.
> 
> ```
> PING_PROXY_SERVER_USING_IP_ADDRESS=false
> ```
> 
> and then run update once.
> 
> ```
> cd /var/www/minetrax
> sh update.sh
> ```

Well and i tried pinging on

> Try entering your IP:PORT in some PING check site like https://mcsrvstat.us/ and see if it show online there. Most likely its not accessible from web and you might consider changing config to let Minetrax do PING via hostname (eg: play.xxxxxxxxx.com) instead.
> 
> To force Minetrax to PING proxy using hostname instead of ip:port plz change this .env variable to `false`.
> 
> ```
> PING_PROXY_SERVER_USING_IP_ADDRESS=false
> ```
> 
> and then run update once.
> 
> ```
> cd /var/www/minetrax
> sh update.sh
> ```

I tried that with the server status but the problem is:
![image](https://github.com/user-attachments/assets/13ecc5d6-f20c-4071-bece-eba440296f61)
