### ISSUE TITLE
The get method is not supported for ruote api/v1/account-link/verify.Supported methods: POST.

### ISSUE THREAD

**Issue by errcruze** [MineTrax/minetrax#396]
What to do here and also have a websocket error:
 [Minetrax] ReportServerConsole.reportSync : 405 : Method Not Allowed : {
    "message": "The GET method is not supported for route api/v1/server/console. Supported methods: POST."

**Comment by Xinecraft** [comment]
This is a redirect issue.
It happens when you have the `host-host` set to HTTP in your config.yml but your site is actually on HTTPS.
Open `config.yml` and change `api-host` from  `http://.......................` to `https://..........................`

**Comment by errcruze** [comment]
Yes Mr. PF has helped me, its already resolved.
Thanks.
